### PR TITLE
ndk-build: Use LLVM binutils when GNU binutils are removed (r23+)

### LINKED ISSUE #135: Error: Path "android-sdk/ndk/23.0.7196353/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar" doesn't exist.
Not seeing this file in ndk version 23, it is present in version 22.

### PR DESCRIPTION
**Pull request by MarijnS95**
Since [r21] LLVM binutils are included _for testing_;
Since [r22] GNU binutils are deprecated in favour of LLVM's;
Since [r23] GNU binutils have been removed.

When GNU binutils are not available (`<triple>-<bin_name>`) "fall back" to `llvm-<bin_name>` binaries from LLVM binutils that are now included with the NDK.

To maintain stability with the current ndk-build crate release, prefer GNU binutils for as long as it is provided by the NDK instead of trying to use `llvm-<bin_name>` from r21 onwards.

[r21]: https://github.com/android/ndk/wiki/Changelog-r21
[r22]: https://github.com/android/ndk/wiki/Changelog-r22
[r23]: https://github.com/android/ndk/wiki/Changelog-r23

Fixes #135

---

We could also opt for LLVM binutils in r22 (requires extra logic to figure out whether we're building on r21 or r22) where GNU binutils are technically deprecated, but since the current crate release already uses that successfully there seems no need to change it at risk of breaking projects that are somehow incompatible.

### CODE REVIEW

File: ndk-build/src/ndk.rs [hunk 1]
```diff
@@ -196,22 +196,29 @@ impl Ndk {
...
+        // as long as it is provided by the NDK instead of trying to use llvm-* from r21 onwards.
+        let gnu_bin = toolchain_bin.join(format!("{}-{}{}", target.ndk_triple(), name, ext));
+        if gnu_bin.exists() {
+            Ok(gnu_bin)
+        } else {
+            let llvm_bin = toolchain_bin.join(format!("llvm-{}{}", name, ext));
+            llvm_bin
+                .exists()
+                .then(|| llvm_bin)
+                .ok_or_else(|| NdkError::PathNotFound(gnu_bin))
```
Comment (MarijnS95) [inline ndk-build/src/ndk.rs:220]: Not sure if we should print the GNU or LLVM bin in the error. Theoretically LLVM is only going to become relevant in the future, but for now we might want to have both... "Could not find <gnu binutils> tool nor <llvm binutils> tool".

Comment (msiglreith) [reply ndk-build/src/ndk.rs:220]: A dedicated error case would be nice imo

Comment (MarijnS95) [reply ndk-build/src/ndk.rs:220]: I totally agree. How's this:

```console
me:android-ndk-rs/ $ cargo apk run -p ndk-examples
Error: GNU toolchain binary `aarch64-linux-android-ar` nor LLVM toolchain binary `llvm-ar` found in `"/home/marijn/Android/Sdk/ndk/23.0.7196353/toolchains/llvm/prebuilt/linux-x86_64/bin"`
```

**Review by msiglreith — APPROVED** [review]
